### ISSUE TITLE
[User Story 15] Horizontal Card Columns

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#159]
### User Story Title

| Risk | Priority | Story Points |
| :---: | :---: | :---: | 
| Medium | Medium | **3** |  

As a user when browsing through ads on classifiedz I should be able to see them from left to right instead of top to bottom.
```
1  4  7      1  2  3
2  5  8      4  5  6
3  6  9      7  8  9
```
A possible sultion to this problem is to use [masonry.js](https://masonry.desandro.com/options.html#horizontalorder)

- [x] 15.1 Switch from Bootstrap to Masonry.JS for cards #198 (**3 Hours**) 
- [x] 15.2 Apply changes to all pages of the project #199 (**2 Hours**)

**Comment by neqqash** [comment]
I looked into this, many people have had the same issue. by default it goes from top to bottom rather than left to right. I did not find a definite solution and neither has anyone else that i know of, i will try looking more into it but in the worst case, we should leave it as is, what do you guys think? @kcamcam @rami186 @BrandonBalala @laurie-y @monnyy @HanGao2333 @Swallow666

**Comment by kevcamel** [comment]
<img width="720" alt="screen shot 2017-11-03 at 9 01 59 pm" src="https://user-images.githubusercontent.com/16027312/32400732-42e02b00-c0da-11e7-9155-c0f1a33c35d8.png">
