### ISSUE TITLE
Issue when implement 'your store' button

### ISSUE THREAD

**Issue by Swallow666** [classifiedz/classifiedz.github.io#27]
I am working on this, when users didn't registered yet click 'your store' button, the page jump to login page so that they can login or register, and if they already registered --->'your store' .

But since I want to implement this feature, the 'your store' button in navbar would be different between unregistered users and login users, so I'm confused about how to implement this. 

I don't think we should create another home page for login users, then how? Can I solve this problem in html&css? or there is a method we can solve it in Javascript (I don't know about js)?

**Comment by neqqash** [comment]
you bring up a good point, i also  think we should only enable the "your store" element once the user has logged in. which is why i proposed that once a user has accessed the website, they are directed to  either log in or register and then we can bring them to the home page. im not sure how to do myself

**Comment by laurie-y** [comment]
I don't think you two have the same idea in mind. 

From what I understood, he still wants the option "Your Store" to be seen by users whether they're registered/logged in or not. The difference would be that if they are not yet registered/logged in, then clicking the button would redirect them to the login page where they can sign in/create an account before accessing "Your Store".

I think the idea is similar to Kijiji where there's the "Post Ad" button that's visible whether you're signed in or not but where it directs you is dependent on that factor. If you click it when you're not signed in, it'll ask you to either register or log in.

The issue with directing them straight to the login or register page when they access the website is that the user won't get a clear idea of what the site is for. I think it's best if users can browse without an account and then only need to register/log in if they find something they want to buy or if they want to sell something. It's also better because it gives users the ability to share listings to friends that they think might be interested. If friends need to create an account to see a listing that was shared to them, it might dissuade them from the site.

**Comment by neqqash** [comment]
that sounds good too, i was thinking of another implementation, but this way seems good too, and it does show users what the website is about rather than forcing them to log in/register right off the bat

**Comment by kevcamel** [comment]
good point and very relevant questions and answers 🙂  
@Swallow666 you could close this current issue, create a new issue to resolve this feature in sprint 3 👍

**Comment by laurie-y** [comment]
Rather than close it and open the same issue, you can just move the milestone

**Comment by Swallow666** [comment]
sounds good, I will move this to milestone sprint 3.
